apiVersion: v1
kind: Namespace
metadata:
  name: sno03
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: hub-cluster
  namespace: sno03
  labels:
    app: ztp-application
spec:
  clusterSelector:
    matchLabels:
      local-cluster: 'true'
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  annotations:
    apps.open-cluster-management.io/reconcile-rate: high
  name: ztp-repository
  namespace: sno03
spec:
  type: Git
  pathname: 'https://github.com/pandeybk/rhacm-gitops-workshop.git'
  insecureSkipVerify: false
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: cluster-sno03-telco-ocp-run
  namespace: sno03
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values: 
          - cluster-sno03-telco-ocp-run
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: resources/ocp-clusters/sno03.telco.ocp.run
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: cluster-sno03-telco-ocp-run
  name: cluster-sno03-tor-subscription-1
  namespace: sno03
spec:
  channel: sno03/ztp-repository
  placement:
    placementRef:
      kind: PlacementRule
      name: hub-cluster
