apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
resources:
- 00-namespace.yaml
- 01-operator-group.yaml
- 02-subscription.yaml
- 03-multiclusterhub.yaml
