
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: advance-cluster-management-governance
  namespace: openshift-gitops
spec:
  generators:
  - list:
      elements: 
      - name: in-cluster 
  template:
    metadata:
      name: advance-cluster-management-{{name}}
    spec:
      project: advance-cluster-management
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      source:
        repoURL: https://github.com/pandeybk/rhacm-gitops-workshop.git
        targetRevision: main
        path: resources/rhacm-governance
      destination:
        server: 'https://kubernetes.default.svc'
