apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: bookinfo-dev
  namespace: openshift-gitops
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: gitops-clusters
        requeueAfterSeconds: 180
  template:
    metadata:
      name: bookinfo-dev-{{name}}
      labels:
        velero.io/exclude-from-backup: "true"
    spec:
      project: default
      source:
        repoURL: https://github.com/pandeybk/rhacm-gitops-workshop.git
        targetRevision: main
        path: resources/workloads/bookinfo/overlays/dev
      destination:
        namespace: bookinfo-dev
        server: "{{server}}"
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
          - PruneLast=true
---
