apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: podinfo-dev
  namespace: openshift-gitops
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: gitops-clusters
        requeueAfterSeconds: 180
  template:
    metadata:
      name: 'podinfo-{{name}}'
    spec:
      project: "webapps"
      source:
        repoURL: https://github.com/pandeybk/rhacm-gitops-workshop.git
        targetRevision: main
        path: resources/workloads/podinfo
      destination:
        server: '{{server}}'
        namespace: podinfo-dev
      syncPolicy:
        automated:
          selfHeal: true
        syncOptions:
            - CreateNamespace=true
---